import { Container } from "../components/ui/Container";
import { Reveal } from "../components/ui/Reveal";
import { StoryBand } from "../components/sections/StoryBand";
import { VerticalTabs } from "../components/sections/VerticalTabs";
import { CardGrid } from "../components/sections/CardGrid";

// ✅ Edit content directly here.
const INTRO =
  "We tackle the technology gaps that prevent real‑time, accurate landslide monitoring at large scale.";

const EXISTING_TECH_INTRO =
  "Current monitoring approaches provide useful data but have limitations for real‑time detection.";

const EXISTING_TECH_BULLETS: string[] = [
  "Geophysical and geodetic technologies, such as seismometers and ground penetration radar, can obtain near real-time and accurate measurement of individual locations, but landslide sites are often large-scale areas and the limited coverage of such technologies at specific time may result in missing key indicators related to landslides. Moreover, these instruments often require manual calibration and operation onsite and may cause high risks to personnel in landslide-prone areas",
  "Meteorological sensors, such as rain gauges and soil moisture sensors, offer real-time measurements of the ambient environmental conditions. They provide comprehensive measurements for analysing the triggering factors but have high uncertainty if directly used for landslide prediction as they only capture indirect signals",
  "Remote sensing methods, such as optical sensors and inSAR radars on airborne platforms, can cover large-scale areas. They have been used to scan large regions for building an inventory of landslide hazards rather than real-time monitoring and detection, because they are constrained by the intrinsic trade-off between spatial and temporal resolutions. In response to the increasing threats of disastrous landslides, there is an urgent need to research and develop a new generation of real-time and accurate landslide monitoring and prediction technologies"
];

const CHALLENGES: string[] = [
  "Many sensors deployed for continuous landslide monitoring in remote areas require reliable and long-term power supply and data communication. However, replacing depleted batteries in densely deployed sensors across large and hazardous landslide-prone areas is often costly and dangerous.",
  "The high volumes of measurement streams generated by a large quantity of sensors require reliable transmission in real-time, but landslide sites often have complex geographical barriers and poor wireless network coverage, causing disruption and outage issues that inhibit real-time data transmission.",
  "Existing generic AI/ML models lack an understanding of the underlying physical constraints implicitly present in the training data, which can hinder their ability to deliver reliable and accurate inferences when processing real-world, noisy landslide monitoring sensor data acquired under varying environmental conditions."
];

const BOTTLENECKS: { title: string; text: string }[] = [
  {
    title: "Power & maintenance",
    text: "Long‑term energy for remote dense sensors without dangerous battery replacement.",
  },
  {
    title: "Coverage & reliability",
    text: "Robust transmission despite complex terrain and weak wireless coverage.",
  },
  {
    title: "Model trustworthiness",
    text: "Reliable inference under noisy, changing real‑world conditions.",
  },
];

export function OurWorkPage() {
  return (
    <>
      <StoryBand
        kicker="Our Work"
        title="Bridging sensing, communications and AI to overcome real‑world constraints"
        imageUrl="/images/technology.svg"
      >
        <p className="m-0">{INTRO}</p>
      </StoryBand>

      <StoryBand
        kicker="Existing technology"
        title="What exists today — and the limitations for real‑time monitoring"
        imageUrl="/images/hero.svg"
      >
        <p className="m-0">{EXISTING_TECH_INTRO}</p>
        <VerticalTabs
          tabs={[
            {
              title: "Geophysical & Geodetic",
              body: EXISTING_TECH_BULLETS[0] ?? "",
            },
            {
              title: "Meteorological Sensors",
              body: EXISTING_TECH_BULLETS[1] ?? "",
            },
            {
              title: "Remote Sensing",
              body: EXISTING_TECH_BULLETS[2] ?? "",
            },
          ]}
        />
      </StoryBand>

      <StoryBand
        kicker="Challenges"
        title="Three core challenges that inhibit real‑time large‑scale deployment"
        imageUrl="/images/challenges.svg"
      >
        <VerticalTabs
          tabs={[
            {
              title: "Challenge 1: Power Supply",
              body: CHALLENGES[0] ?? "",
            },
            {
              title: "Challenge 2: Data Transmission",
              body: CHALLENGES[1] ?? "",
            },
            {
              title: "Challenge 3: AI/ML Reliability",
              body: CHALLENGES[2] ?? "",
            },
          ]}
        />
      </StoryBand>

      <StoryBand kicker="Bottlenecks" title="What we aim to overcome" imageUrl="/images/workpackages.svg">
        <CardGrid items={BOTTLENECKS} />
      </StoryBand>

      <section className="py-14 bg-bg">
        <Container>
          <Reveal>
            <div className="text-xs font-extrabold tracking-[.14em] uppercase text-black/70">Next</div>
            <h2 className="font-serif text-forest2 text-[clamp(30px,3.2vw,46px)] tracking-[-0.01em] leading-[1.05] mt-3">
              See how we measure success
            </h2>
            <p className="max-w-[80ch] text-black/70 leading-[1.8] mt-3">
              Our Impact describes the research objectives, work packages, and validation metrics.
            </p>
            <a href="/#/our-impact" className="btn btnDark mt-3 inline-flex">
              Go to Our Impact →
            </a>
          </Reveal>
        </Container>
      </section>
    </>
  );
}
