import { Container } from "../components/ui/Container";
import { Reveal } from "../components/ui/Reveal";
import { StoryBand } from "../components/sections/StoryBand";
import { VerticalTabs } from "../components/sections/VerticalTabs";
import { CardGrid } from "../components/sections/CardGrid";

// ✅ Edit content directly here.
const INTRO =
  "We tackle the technology gaps that prevent real‑time, accurate landslide monitoring at large scale.";

const EXISTING_TECH_INTRO =
  "Current monitoring approaches provide useful data but have limitations for real‑time detection.";

const EXISTING_TECH_BULLETS: string[] = [
  "Geophysical and geodetic technologies, such as seismometers and ground penetration radar, can obtain near real-time and accurate measurement of individual locations, but landslide sites are often large-scale areas and the limited coverage of such technologies at specific time may result in missing key indicators related to landslides. Moreover, these instruments often require manual calibration and operation onsite and may cause high risks to personnel in landslide-prone areas",
  "Meteorological sensors, such as rain gauges and soil moisture sensors, offer real-time measurements of the ambient environmental conditions. They provide comprehensive measurements for analysing the triggering factors but have high uncertainty if directly used for landslide prediction as they only capture indirect signals",
  "Remote sensing methods, such as optical sensors and inSAR radars on airborne platforms, can cover large-scale areas. They have been used to scan large regions for building an inventory of landslide hazards rather than real-time monitoring and detection, because they are constrained by the intrinsic trade-off between spatial and temporal resolutions. In response to the increasing threats of disastrous landslides, there is an urgent need to research and develop a new generation of real-time and accurate landslide monitoring and prediction technologies"
];

const CHALLENGES: string[] = [
  "Many sensors deployed for continuous landslide monitoring in remote areas require reliable and long-term power supply and data communication. However, replacing depleted batteries in densely deployed sensors across large and hazardous landslide-prone areas is often costly and dangerous.",
  "The high volumes of measurement streams generated by a large quantity of sensors require reliable transmission in real-time, but landslide sites often have complex geographical barriers and poor wireless network coverage, causing disruption and outage issues that inhibit real-time data transmission.",
  "Existing generic AI/ML models lack an understanding of the underlying physical constraints implicitly present in the training data, which can hinder their ability to deliver reliable and accurate inferences when processing real-world, noisy landslide monitoring sensor data acquired under varying environmental conditions."
];

const BOTTLENECKS: { title: string; text: string }[] = [
  {
    title: "Power & maintenance",
    text: "Long‑term energy for remote dense sensors without dangerous battery replacement.",
  },
  {
    title: "Coverage & reliability",
    text: "Robust transmission despite complex terrain and weak wireless coverage.",
  },
  {
    title: "Model trustworthiness",
    text: "Reliable inference under noisy, changing real‑world conditions.",
  },
];

const WORK_PACKAGES: { wp: string; title: string; aim: string; novelty: string }[] = [
  {
    wp: "WP1",
    title: "Project Management, Coordination, and Communication",
    aim: "Ensure effective coordination, communication, and management of the project across all partners to deliver high-quality outcomes on time and within budget.",
    novelty: "1) Agile project management methodology\n2) Cross-institutional collaboration framework\n3) Stakeholder engagement and dissemination strategy",
  },
  {
    wp: "WP2",
    title: "Requirement Analysis and System Architecture Design",
    aim: "Conduct comprehensive analysis of typical landslide scenarios and design an integrated architecture to sustainably acquire, transmit and analyze real-time sensor data for accurate landslide prediction.",
    novelty: "1) Comprehensively investigate major types of landslides using novel sensor measurements\n2) Design an intelligent computing and networking architecture to deliver landslide prediction",
  },
  {
    wp: "WP3",
    title: "Optimized RIS for Simultaneous Wireless Power and Information Transfer",
    aim: "Optimize RIS designs for sustainable IoT sensor energy supply and robust wireless communication across large-scale landslide-prone regions (to achieve RO1).",
    novelty: "1) Optimization methodology for active RIS to achieve ideal SWIPT\n2) Efficient and real-time CSI acquisition technology\n3) Innovative RIS-SWIPT testbed for comprehensive evaluation of QoS",
  },
  {
    wp: "WP4",
    title: "Intelligent and Ultra-Low Latency IoT Networking Technologies",
    aim: "Deliver novel designs of an intelligent and ultra-low latency IoT network to securely transmit real-time measurements acquired by large-scale heterogeneous sensors covering extensive landslide areas (to achieve RO2).",
    novelty: "1) Innovative and intelligent IoT network architecture\n2) Integrated computing and networking framework\n3) Lightweight and interpretable AI-based IoT abnormality mitigation technologies",
  },
  {
    wp: "WP5",
    title: "Knowledge-guided and Explainable AI/ML Approach",
    aim: "Create reliable, knowledge-guided, and explainable AI/ML models to accurately predict landslides by integrating real-time sensor measurements, remote sensing data, and environmental information (to achieve RO3).",
    novelty: "1) High-performance knowledge-guided transformer model\n2) Adversarial and transfer learning method to enhance robustness\n3) Integration of Grad-CAM, SHAP and causal reasoning to understand decision chains",
  },
  {
    wp: "WP6",
    title: "System Integration, Experiments, Demonstration and Evaluation",
    aim: "Integrate individual R&I outcomes into an experiment system and perform comprehensive simulated and real-world experiments for performance evaluation, refinement, and demonstration (to achieve RO4).",
    novelty: "1) Test platform for testing the integrated system\n2) Comprehensive performance and reliability tests of the novel prediction system\n3) Real-world demonstrations to catalyze innovations in broader environmental monitoring",
  },
];

export function OurWorkPage() {
  return (
    <>
      <StoryBand
        kicker="Our Work"
        title="Bridging sensing, communications and AI to overcome real‑world constraints"
        className="bg-blue-950"
      >
        <p className="m-0">{INTRO}</p>
      </StoryBand>

      {/* Work Packages - Main Section */}
      <StoryBand kicker="Work Packages" title="WP1–WP6: Our Programme Structure" colorIndex={0}>
        <p className="m-0 mb-6">
          INSTANT is organized into six integrated work packages, each targeting specific challenges in landslide monitoring and prediction.
        </p>
        <div className="grid grid-cols-12 gap-3">
          {WORK_PACKAGES.map((wp, idx) => (
            <Reveal key={wp.wp} delayMs={idx * 60} className="col-span-12 md:col-span-6">
              <div className="border border-black/10 bg-white rounded-2xl overflow-hidden h-full shadow-sm">
                <div className="p-4 border-b border-black/10 bg-gray-50">
                  <div className="inline-flex px-3 py-1.5 rounded-full border border-forest/25 bg-forest/10 font-extrabold text-xs tracking-[.14em] uppercase text-forest">
                    {wp.wp}
                  </div>
                  <div className="mt-3 font-extrabold text-forest2 tracking-[-0.01em]">{wp.title}</div>
                </div>
                <div className="p-4">
                  <div className="text-xs font-extrabold tracking-[.14em] uppercase text-forest">Aim</div>
                  <div className="mt-2 text-black/75 text-[13px] leading-[1.75] whitespace-pre-wrap">{wp.aim}</div>
                  <div className="mt-4 text-xs font-extrabold tracking-[.14em] uppercase text-forest">Novelty</div>
                  <div className="mt-2 text-black/75 text-[13px] leading-[1.75] whitespace-pre-wrap">{wp.novelty}</div>
                </div>
              </div>
            </Reveal>
          ))}
        </div>
      </StoryBand>

      <StoryBand
        kicker="Existing technology"
        title="What exists today — and the limitations for real‑time monitoring"
        colorIndex={1}
      >
        <p className="m-0">{EXISTING_TECH_INTRO}</p>
        <VerticalTabs
          light
          tabs={[
            {
              title: "Geophysical & Geodetic",
              body: EXISTING_TECH_BULLETS[0] ?? "",
            },
            {
              title: "Meteorological Sensors",
              body: EXISTING_TECH_BULLETS[1] ?? "",
            },
            {
              title: "Remote Sensing",
              body: EXISTING_TECH_BULLETS[2] ?? "",
            },
          ]}
        />
      </StoryBand>

      <StoryBand
        kicker="Challenges"
        title="Three core challenges that inhibit real‑time large‑scale deployment"
        colorIndex={0}
      >
        <VerticalTabs
          light
          tabs={[
            {
              title: "Challenge 1: Power Supply",
              body: CHALLENGES[0] ?? "",
            },
            {
              title: "Challenge 2: Data Transmission",
              body: CHALLENGES[1] ?? "",
            },
            {
              title: "Challenge 3: AI/ML Reliability",
              body: CHALLENGES[2] ?? "",
            },
          ]}
        />
      </StoryBand>

      <StoryBand kicker="Bottlenecks" title="What we aim to overcome" colorIndex={1}>
        <CardGrid items={BOTTLENECKS} light />
      </StoryBand>

      <section className="py-14 bg-bg">
        <Container>
          <Reveal>
            <div className="text-xs font-extrabold tracking-[.14em] uppercase text-black/70">Next</div>
            <h2 className="font-serif text-forest2 text-[clamp(30px,3.2vw,46px)] tracking-[-0.01em] leading-[1.05] mt-3">
              See how we measure success
            </h2>
            <p className="max-w-[80ch] text-black/70 leading-[1.8] mt-3">
              Our Impact describes the research objectives and validation metrics.
            </p>
            <a href="/#/our-impact" className="btn btnDark mt-3 inline-flex">
              Go to Our Impact →
            </a>
          </Reveal>
        </Container>
      </section>
    </>
  );
}
